version: '3.8'

services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:16-alpine
    container_name: postgres_learning1
    environment:
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: postgres1
      POSTGRES_DB: learn_db
    ports:
      - "2128:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./lesson.sql:/docker-entrypoint-initdb.d/lesson.sql
    restart: unless-stopped

volumes:
  postgres_data: